[package]
name = "cargo-compete"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand for competitive programming."
publish = false

[dependencies]
anyhow = "1.0.32"
atty = "0.2.14"
az = "1.0.0"
base64 = "0.12.3"
cargo-member = "0.1.2"
cargo_metadata = "0.11.1"
combine = "4.2.1"
dirs = "3.0.1"
easy-ext = "0.2.2"
fwdansi = "1.1.0"
heck = "0.3.1"
human-size = "0.4.1"
indexmap = { version = "1.5.0", features = ["serde-1"] }
indicatif = "0.15.0"
itertools = "0.9.0"
maplit = "1.0.2"
opener = "0.4.1"
prettytable-rs = "0.8.0"
reqwest = { version = "0.10.7", default-features = false, features = ["blocking"] }
rpassword = "4.0.5"
rprompt = "1.0.5"
semver = "0.10.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.13"
shell-escape = "0.1.5"
snowchains_core = { version = "0.0.0", git = "https://github.com/qryxip/snowchains", rev = "b878e8aebfdb1142ff48f0b1399ce7623bab8fb3" }
structopt = "0.3.15"
strum = { version = "0.18.0", features = ["derive"] }
tempfile = "3.1.0"
termcolor = "1.1.0"
tokio = { version = "0.2.22", features = ["signal"] }
toml = "0.5.6"
toml_edit = "0.2.0"
url = "2.1.1"
which = "4.0.1"

[target.'cfg(windows)'.dependencies]
term_size = "1.0.0-beta.2"
