[package]
name = "cargo-compete"
version = "0.3.1"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand for competitive programming."
repository = "https://github.com/qryxip/cargo-compete"
readme = "README.md"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[dependencies]
anyhow = "1.0.32"
atty = "0.2.14"
az = "1.0.0"
base64 = "0.12.3"
cargo-member = "0.1.2"
cargo_metadata = "0.11.1"
derivative = "2.1.1"
dirs = "3.0.1"
easy-ext = "0.2.2"
fwdansi = "1.1.0"
heck = "0.3.1"
human-size = "0.4.1"
indexmap = { version = "1.5.0", features = ["serde-1"] }
indicatif = "0.15.0"
itertools = "0.9.0"
liquid = "0.21.1"
liquid-core = "0.21.1"
liquid-derive = "0.21.0"
maplit = "1.0.2"
opener = "0.4.1"
pretty_assertions = "0.6.1"
prettytable-rs = "0.8.0"
reqwest = { version = "0.10.7", default-features = false, features = ["blocking"] }
rpassword = "4.0.5"
rprompt = "1.0.5"
semver = "0.10.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.13"
shell-escape = "0.1.5"
snowchains_core = "0.3.1"
structopt = "0.3.16"
strum = { version = "0.19.2", features = ["derive"] }
tempfile = "3.1.0"
termcolor = "1.1.0"
tokio = { version = "0.2.22", features = ["signal"] }
toml = "0.5.6"
toml_edit = "0.2.0"
url = { version = "2.1.1", features = ["serde"] }
which = "4.0.2"

[target.'cfg(windows)'.dependencies]
term_size = "=1.0.0-beta.2"
