[package]
name = "cargo-compete"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand for competitive programming."
publish = false

[dependencies]
anyhow = "1.0.32"
atty = "0.2.14"
cargo-member = "0.1.2"
cargo_metadata = "0.11.1"
dirs = "3.0.1"
fwdansi = "1.1.0"
indicatif = "0.15.0"
itertools = "0.9.0"
reqwest = { version = "0.10.7", default-features = false, features = ["blocking"] }
rpassword = "4.0.5"
rprompt = "1.0.5"
semver = "0.10.0"
serde = { version = "1.0.114", features = ["derive"] }
shell-escape = "0.1.5"
snowchains_core = { version = "0.0.0", git = "https://github.com/qryxip/snowchains", rev = "b878e8aebfdb1142ff48f0b1399ce7623bab8fb3" }
structopt = "0.3.15"
strum = { version = "0.18.0", features = ["derive"] }
termcolor = "1.1.0"
toml = "0.5.6"
toml_edit = "0.2.0"
which = "4.0.1"
easy-ext = "0.2.2"
url = "2.1.1"
serde_json = "1.0.57"
heck = "0.3.1"

[target.'cfg(windows)'.dependencies]
term_size = "1.0.0-beta.2"
